services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

#  ngrok:
#    image: wernight/ngrok
#    container_name: ngrok
#    depends_on:
#      - jenkins
#    environment:
#      - NGROK_AUTHTOKEN=2voQo4BRiez4xTHq7GP2kh0URV6_5XM3TZqXGaWaeLcVNTgMz
#      - NGROK_REGION=in
#    ports:
#      - "4040:4040"  # Optional: access ngrok's dashboard
#    command: ngrok http jenkins:8080

volumes:
  jenkins_home: